// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7NiJQ0fsVqS6Fjqz8yy1Q2g6Akj8frK0',
    appId: '1:109626496368:web:8ce71e1d36b2f2fc142bb5',
    messagingSenderId: '109626496368',
    projectId: 'ecommerce-app-7669',
    authDomain: 'ecommerce-app-7669.firebaseapp.com',
    storageBucket: 'ecommerce-app-7669.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIkgR_eXR7vW-aWwqdg08FzB_yFXkIdlw',
    appId: '1:109626496368:android:5834e41a6253b634142bb5',
    messagingSenderId: '109626496368',
    projectId: 'ecommerce-app-7669',
    storageBucket: 'ecommerce-app-7669.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwjiTcPcVrTbdg9rKYWlAnkMIh7jzgJZQ',
    appId: '1:109626496368:ios:3a968628e8f8888b142bb5',
    messagingSenderId: '109626496368',
    projectId: 'ecommerce-app-7669',
    storageBucket: 'ecommerce-app-7669.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceAdminApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwjiTcPcVrTbdg9rKYWlAnkMIh7jzgJZQ',
    appId: '1:109626496368:ios:3a968628e8f8888b142bb5',
    messagingSenderId: '109626496368',
    projectId: 'ecommerce-app-7669',
    storageBucket: 'ecommerce-app-7669.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceAdminApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA7NiJQ0fsVqS6Fjqz8yy1Q2g6Akj8frK0',
    appId: '1:109626496368:web:6c936a9e2688a0f4142bb5',
    messagingSenderId: '109626496368',
    projectId: 'ecommerce-app-7669',
    authDomain: 'ecommerce-app-7669.firebaseapp.com',
    storageBucket: 'ecommerce-app-7669.firebasestorage.app',
  );
}
